vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix: /assets/images/posts
            upload_destination: '%kernel.project_dir%/public/assets/images/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
